// <auto-generated />
using System;
using FlightReservationAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightReservationAPI.Migrations
{
    [DbContext(typeof(FlightDataBaseContext))]
    partial class FlightDataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlightReservationAPI.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("RolID");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id")
                        .HasName("PK__Kullanic__3214EC2764E5AB69");

                    b.HasIndex("RolId");

                    b.HasIndex(new[] { "Eposta" }, "UQ__Kullanic__03ABA3918430F333")
                        .IsUnique();

                    b.ToTable("Kullanici", (string)null);
                });

            modelBuilder.Entity("FlightReservationAPI.Models.RezervasyonDetaylari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RezervasyonId")
                        .HasColumnType("int")
                        .HasColumnName("RezervasyonID");

                    b.HasKey("Id")
                        .HasName("PK__Rezervas__3214EC275A470D71");

                    b.HasIndex("RezervasyonId");

                    b.ToTable("RezervasyonDetaylari", (string)null);
                });

            modelBuilder.Entity("FlightReservationAPI.Models.Rezervasyonlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BebekSayisi")
                        .HasColumnType("int");

                    b.Property<int>("CocukSayisi")
                        .HasColumnType("int");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int")
                        .HasColumnName("KullaniciID");

                    b.Property<DateTime>("RezervasyonTarihi")
                        .HasColumnType("datetime");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("UcusId")
                        .HasColumnType("int")
                        .HasColumnName("UcusID");

                    b.Property<int>("UcusSinifiId")
                        .HasColumnType("int")
                        .HasColumnName("UcusSinifiID");

                    b.Property<int>("YetişkinSayisi")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Rezervas__3214EC27CACA67A6");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("UcusId");

                    b.HasIndex("UcusSinifiId");

                    b.ToTable("Rezervasyonlar", (string)null);
                });

            modelBuilder.Entity("FlightReservationAPI.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Rol__3214EC2702491D85");

                    b.HasIndex(new[] { "RolAdi" }, "UQ__Rol__85F2635D25C128D8")
                        .IsUnique();

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("FlightReservationAPI.Models.UcusSiniflari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("FiyatOrani")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("SinifAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__UcusSini__3214EC27A8BD1B9D");

                    b.ToTable("UcusSiniflari", (string)null);
                });

            modelBuilder.Entity("FlightReservationAPI.Models.UcusSiniflariBaglantisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("SinifFiyati")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("UcusId")
                        .HasColumnType("int")
                        .HasColumnName("UcusID");

                    b.Property<int>("UcusSinifiId")
                        .HasColumnType("int")
                        .HasColumnName("UcusSinifiID");

                    b.HasKey("Id")
                        .HasName("PK__UcusSini__3214EC27E56687BF");

                    b.HasIndex("UcusId");

                    b.HasIndex("UcusSinifiId");

                    b.ToTable("UcusSiniflariBaglantisi", (string)null);
                });

            modelBuilder.Entity("FlightReservationAPI.Models.Ucuslar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BosKoltukSayisi")
                        .HasColumnType("int");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("KalkisSehri")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("KalkisTarihi")
                        .HasColumnType("datetime");

                    b.Property<int>("KoltukSayisi")
                        .HasColumnType("int");

                    b.Property<string>("UcusTuru")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VarisSehri")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Ucuslar__3214EC27D660EE48");

                    b.ToTable("Ucuslar", (string)null);
                });

            modelBuilder.Entity("FlightReservationAPI.Models.VwRezervasyonViewModel", b =>
                {
                    b.Property<decimal?>("FiyatOrani")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("KalkisSehri")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SinifAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UcusSinifId")
                        .HasColumnType("int");

                    b.Property<string>("VarisSehri")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable((string)null);

                    b.ToView("vw_RezervasyonViewModel", (string)null);
                });

            modelBuilder.Entity("FlightReservationAPI.Models.Kullanici", b =>
                {
                    b.HasOne("FlightReservationAPI.Models.Rol", "Rol")
                        .WithMany("Kullanicis")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK__Kullanici__RolID__286302EC");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("FlightReservationAPI.Models.RezervasyonDetaylari", b =>
                {
                    b.HasOne("FlightReservationAPI.Models.Rezervasyonlar", "Rezervasyon")
                        .WithMany("RezervasyonDetaylaris")
                        .HasForeignKey("RezervasyonId")
                        .HasConstraintName("FK__Rezervasy__Rezer__282DF8C2");

                    b.Navigation("Rezervasyon");
                });

            modelBuilder.Entity("FlightReservationAPI.Models.Rezervasyonlar", b =>
                {
                    b.HasOne("FlightReservationAPI.Models.Kullanici", "Kullanici")
                        .WithMany("Rezervasyonlars")
                        .HasForeignKey("KullaniciId")
                        .IsRequired()
                        .HasConstraintName("FK__Rezervasy__Kulla__1F98B2C1");

                    b.HasOne("FlightReservationAPI.Models.Ucuslar", "Ucus")
                        .WithMany("Rezervasyonlars")
                        .HasForeignKey("UcusId")
                        .IsRequired()
                        .HasConstraintName("FK__Rezervasy__UcusI__208CD6FA");

                    b.HasOne("FlightReservationAPI.Models.UcusSiniflari", "UcusSinifi")
                        .WithMany("Rezervasyonlars")
                        .HasForeignKey("UcusSinifiId")
                        .IsRequired()
                        .HasConstraintName("FK__Rezervasy__UcusS__2180FB33");

                    b.Navigation("Kullanici");

                    b.Navigation("Ucus");

                    b.Navigation("UcusSinifi");
                });

            modelBuilder.Entity("FlightReservationAPI.Models.UcusSiniflariBaglantisi", b =>
                {
                    b.HasOne("FlightReservationAPI.Models.Ucuslar", "Ucus")
                        .WithMany("UcusSiniflariBaglantisis")
                        .HasForeignKey("UcusId")
                        .IsRequired()
                        .HasConstraintName("FK__UcusSinif__UcusI__245D67DE");

                    b.HasOne("FlightReservationAPI.Models.UcusSiniflari", "UcusSinifi")
                        .WithMany("UcusSiniflariBaglantisis")
                        .HasForeignKey("UcusSinifiId")
                        .IsRequired()
                        .HasConstraintName("FK__UcusSinif__UcusS__25518C17");

                    b.Navigation("Ucus");

                    b.Navigation("UcusSinifi");
                });

            modelBuilder.Entity("FlightReservationAPI.Models.Kullanici", b =>
                {
                    b.Navigation("Rezervasyonlars");
                });

            modelBuilder.Entity("FlightReservationAPI.Models.Rezervasyonlar", b =>
                {
                    b.Navigation("RezervasyonDetaylaris");
                });

            modelBuilder.Entity("FlightReservationAPI.Models.Rol", b =>
                {
                    b.Navigation("Kullanicis");
                });

            modelBuilder.Entity("FlightReservationAPI.Models.UcusSiniflari", b =>
                {
                    b.Navigation("Rezervasyonlars");

                    b.Navigation("UcusSiniflariBaglantisis");
                });

            modelBuilder.Entity("FlightReservationAPI.Models.Ucuslar", b =>
                {
                    b.Navigation("Rezervasyonlars");

                    b.Navigation("UcusSiniflariBaglantisis");
                });
#pragma warning restore 612, 618
        }
    }
}
